models:
  Conv1D:
    architecture: # optionally overwrite architecture here
      num_layers: none
      encoding_dim: none
    age_learning_rate: 0.01  # Different learning rate for age predictor
    scale_age_learning_rate: False
    scale_ae_learning_rate: True
    weight_decay: 0.0001
  
  Conv2D:
    architecture: # optionally overwrite architecture here
      num_layers: none
      encoding_dim: none
    age_learning_rate: 0.01  # Different learning rate for age predictor
    scale_age_learning_rate: False
    scale_ae_learning_rate: True  
    weight_decay: 0.0001
  LSTM:
    architecture: # optionally overwrite architecture here
      num_layers: none
      encoding_dim: none
    age_learning_rate: 0.01   # Different learning rate for age predictor
    scale_age_learning_rate: False
    scale_ae_learning_rate: True
    weight_decay: 0.0001

# Loss function configuration
loss_function:
  age_lambda: 0.6
  separation_lambda: 0
  pseudo_age: False
  
# Random seed configuration
overwrite_seed: none